class contactNoRunner {
	public static void main (String chand[]){
		long contact;
		contact = contactNo.getcontactNo("Chandana");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Sagar");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Manjunath");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("kiran");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Nagraj");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Swathi");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Sararth");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Likith");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Akshay");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Abhay");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Anjali");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Arun");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Akash");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Amithsharma");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Amitha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("Ankitha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("rajroy");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("shivrudra");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("shanmugham");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("smitha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("shravani");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("harshitha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("sindhu");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("neetha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("raksha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("chaitanya");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("bhoomika");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("kushani");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("dharshan");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("ankith");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("gowri");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("ganesh");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("meghana");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("ananya");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("samrudhi");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("varsha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("pallavi");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("surya");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("rakshith");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("ranjith");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("aishwarya");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("vanitha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("sahana");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("sanjana");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("varshitha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("bhavana");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("pavithra");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("pusphitha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("swetha");
		System.out.println("The contact no is "+contact);
		contact = contactNo.getcontactNo("nikitha");
		System.out.println("The contact no is "+contact);
	}
}
		
		