class countryCodeRunner{
	public static void main(String chand[]){
		int country = countryCode.getCountryCode("India");
		System.out.println("the country code is "+country);
	    country = countryCode.getCountryCode("Australia");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("SriLanka");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("America");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Afghanistan");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Albania");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Algeria");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Andorra");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Angola");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Argentina");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Armenia");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Aruba");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Austria");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Azebaijan");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Bahamas");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Bahrain");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Bangladesh");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Barbados");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Belarus");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Belgium");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Beliza");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Benin");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Bhutan");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Bolivia");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Bosnia and Herzegovina");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Botswana");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Brazil");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Brunaei");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Bulgaria");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Burkina Faso");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Burundi");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Cambodia");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Cameroon");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Canada");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Cape Verde");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Central African Republic");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Chad");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Chile");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("China");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Colombia");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Comoros");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Congo");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Costa Rica");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Croatia");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Cuba");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Cyprus");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Czech Republic");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Denmark");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Djibouti");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Dominica");
		System.out.println("the country code is "+country);
		country = countryCode.getCountryCode("Dominican Republic");
		System.out.println("the country code is "+country);
			
	}
}
