class FoodPandaRunner {
	public static void main(String chand[]){
		String foodName1 = "Egg Masala";
		double Cost = FoodPanda.getFoodPrice(foodName1);
		System.out.println("The foodName is "+foodName1+" with price of "+Cost);
		String foodName2 = "Puff";
		Cost = FoodPanda.getFoodPrice(foodName2);
		System.out.println("The foodName is "+foodName2+" with price of "+Cost);
		String foodName3 = "Veggi Spring Rolls";
		Cost = FoodPanda.getFoodPrice(foodName3);
		System.out.println("The foodName is "+foodName3+" with price of "+Cost);
		String foodName4 = "Chicken lolipop";
		Cost = FoodPanda.getFoodPrice(foodName4);
		System.out.println("The foodName is "+foodName4+" with price of "+Cost);
		String foodName5 = "Veg Thali";
		Cost = FoodPanda.getFoodPrice(foodName5);
		System.out.println("The foodName is "+foodName5+" with price of "+Cost);
		String foodName6 = "Burger";
		Cost = FoodPanda.getFoodPrice(foodName6);
		System.out.println("The foodName is "+foodName6+" with price of "+Cost);
		String foodName7 = "Pizza";
		Cost = FoodPanda.getFoodPrice(foodName7);
		System.out.println("The foodName is "+foodName7+" with price of "+Cost);
		String foodName8 = "Pasta";
		Cost = FoodPanda.getFoodPrice(foodName8);
		System.out.println("The foodName is "+foodName8+" with price of "+Cost);
		String foodName9 = "Samosa";
		Cost = FoodPanda.getFoodPrice(foodName9);
		System.out.println("The foodName is "+foodName9+" with price of "+Cost);
		String foodName10 = "Buritto";
		Cost = FoodPanda.getFoodPrice(foodName10);
		System.out.println("The foodName is "+foodName10+" with price of "+Cost);
		String foodName11 = "Fried Chicken";
		Cost = FoodPanda.getFoodPrice(foodName11);
		System.out.println("The foodName is "+foodName11+" with price of "+Cost);
		String foodName12 = "Sandwich";
		Cost = FoodPanda.getFoodPrice(foodName12);
		System.out.println("The foodName is "+foodName12+" with price of "+Cost);
		String foodName13 = "Momos";
		Cost = FoodPanda.getFoodPrice(foodName13);
		System.out.println("The foodName is "+foodName13+" with price of "+Cost);
		String foodName14 = "Ramen";
		Cost = FoodPanda.getFoodPrice(foodName14);
		System.out.println("The foodName is "+foodName14+" with price of "+Cost);
		String foodName15 = "Doner Kebab";
		Cost = FoodPanda.getFoodPrice(foodName15);
		System.out.println("The foodName is "+foodName15+" with price of "+Cost);
		String foodName16 = "Fried Fish";
		Cost = FoodPanda.getFoodPrice(foodName16);
		System.out.println("The foodName is "+foodName16+" with price of "+Cost);
		String foodName17 = "Garlic Bread";
		Cost = FoodPanda.getFoodPrice(foodName17);
		System.out.println("The foodName is "+foodName17+" with price of "+Cost);
		String foodName18 = "Salad";
		Cost = FoodPanda.getFoodPrice(foodName18);
		System.out.println("The foodName is "+foodName18+" with price of "+Cost);
		String foodName19 = "Nachos";
		Cost = FoodPanda.getFoodPrice(foodName19);
		System.out.println("The foodName is "+foodName19+" with price of "+Cost);
		String foodName20 = "Hummus";
		Cost = FoodPanda.getFoodPrice(foodName20);
		System.out.println("The foodName is "+foodName20+" with price of "+Cost);
		String foodName21 = "Pita";
		Cost = FoodPanda.getFoodPrice(foodName21);
		System.out.println("The foodName is "+foodName21+" with price of "+Cost);
		String foodName22 = "Spring Rolls";
		Cost = FoodPanda.getFoodPrice(foodName22);
		System.out.println("The foodName is "+foodName22+" with price of "+Cost);
		String foodName23 = "Mashed Potatoes";
		Cost = FoodPanda.getFoodPrice(foodName23);
		System.out.println("The foodName is "+foodName23+" with price of "+Cost);
		String foodName24 = "Steak";
		Cost = FoodPanda.getFoodPrice(foodName24);
		System.out.println("The foodName is "+foodName24+" with price of "+Cost);
		String foodName25 = "Dim Sum";
		Cost = FoodPanda.getFoodPrice(foodName25);
		System.out.println("The foodName is "+foodName25+" with price of "+Cost);
		String foodName26 = "Lobster Roll";
		Cost = FoodPanda.getFoodPrice(foodName26);
		System.out.println("The foodName is "+foodName26+" with price of "+Cost);
		String foodName27 = "SeaFood Platter";
		Cost = FoodPanda.getFoodPrice(foodName27);
		System.out.println("The foodName is "+foodName27+" with price of "+Cost);
		String foodName28 = "Gluten free Pizza";
		Cost = FoodPanda.getFoodPrice(foodName28);
		System.out.println("The foodName is "+foodName28+" with price of "+Cost);
		String foodName29 = "Truffle Fries";
		Cost = FoodPanda.getFoodPrice(foodName29);
		System.out.println("The foodName is "+foodName29+" with price of "+Cost);
		String foodName30 = "Curd Rice";
		Cost = FoodPanda.getFoodPrice(foodName30);
		System.out.println("The foodName is "+foodName30+" with price of "+Cost);
	}
}