class KfcRunner{
	public static void main(String chand[]){
		String mealName1 = "Wednesday Bucket";
		double price = Kfc.getmealPrice(mealName1);
		System.out.println("The meal name is " +mealName1+ " with price is " +price);
		String mealName2 = "Strips Bucket";
		price = Kfc.getmealPrice(mealName2);
		System.out.println("The meal name is " +mealName2+ " with price is " +price);
		String mealName3 = "5pc Leg peice Bucket";
		price = Kfc.getmealPrice(mealName3);
		System.out.println("The meal name is " +mealName3+ " with price is " +price);
		String mealName4 = "10 pc Leg Peice Bucket";
		price = Kfc.getmealPrice(mealName4);
		System.out.println("The meal name is " +mealName4+ " with price is " +price);
		String mealName5 = "Stay Home Bucket";
		price = Kfc.getmealPrice(mealName5);
		System.out.println("The meal name is " +mealName5+ " with price is " +price);
		String mealName6 = "2Dips leg";
		price = Kfc.getmealPrice(mealName6);
		System.out.println("The meal name is " +mealName6+ " with price is " +price);
		String mealName7 = "Family Fest";
		price = Kfc.getmealPrice(mealName7);
		System.out.println("The meal name is " +mealName7+ " with price is " +price);
		String mealName8 = "Ultimate Savings Bucket";
		price = Kfc.getmealPrice(mealName8);
		System.out.println("The meal name is " +mealName8+ " with price is " +price);
		String mealName9 = "Big 12";
		price = Kfc.getmealPrice(mealName9);
		System.out.println("The meal name is " +mealName9+ " with price is " +price);
		String mealName10 = "Mingles Bucket";
		price = Kfc.getmealPrice(mealName10);
		System.out.println("The meal name is " +mealName10+ " with price is " +price);
		String mealName11 = "8pc Hot Crispy And Chicken";
		price = Kfc.getmealPrice(mealName11);
		System.out.println("The meal name is " +mealName11+ " with price is " +price);
		String mealName12 = "Zinger Bucket";
		price = Kfc.getmealPrice(mealName12);
		System.out.println("The meal name is " +mealName12+ " with price is " +price);
		String mealName13 = "Twister Bucket";
		price = Kfc.getmealPrice(mealName13);
		System.out.println("The meal name is " +mealName13+ " with price is " +price);
		String mealName14 = "Double Down Burger";
		price = Kfc.getmealPrice(mealName14);
		System.out.println("The meal name is " +mealName14+ " with price is " +price);
		String mealName15 = "Zinger Burger";
		price = Kfc.getmealPrice(mealName15);
		System.out.println("The meal name is " +mealName15+ " with price is " +price);
		String mealName16 = "Chilli Chicken burger";
		price = Kfc.getmealPrice(mealName16);
		System.out.println("The meal name is " +mealName16+ " with price is " +price);
		String mealName17 = "Veg Zinger";
		price = Kfc.getmealPrice(mealName17);
		System.out.println("The meal name is " +mealName17+ " with price is " +price);
		String mealName18 = "Veg Burger";
		price = Kfc.getmealPrice(mealName18);
		System.out.println("The meal name is " +mealName2+ " with price is " +price);
		String mealName19 = "Double Chicken Roll";
		price = Kfc.getmealPrice(mealName19);
		System.out.println("The meal name is " +mealName19+ " with price is " +price);
		String mealName20 = "Class Chicken Roll";
		price = Kfc.getmealPrice(mealName20);
		System.out.println("The meal name is " +mealName20+ " with price is " +price);
		String mealName21 = "Ricz Bowlz";
		price = Kfc.getmealPrice(mealName21);
		System.out.println("The meal name is " +mealName21+ " with price is " +price);
		String mealName22 = "pepsi";
		price = Kfc.getmealPrice(mealName22);
		System.out.println("The meal name is " +mealName22+ " with price is " +price);
		String mealName23 = "Mountain Dew";
		price = Kfc.getmealPrice(mealName23);
		System.out.println("The meal name is " +mealName23+ " with price is " +price);
		String mealName24 = "Soft Drinks";
		price = Kfc.getmealPrice(mealName24);
		System.out.println("The meal name is " +mealName24+ " with price is " +price);
		String mealName25 = "Milk Shakes";
		price = Kfc.getmealPrice(mealName25);
		System.out.println("The meal name is " +mealName25+ " with price is " +price);
		String mealName26 = "Brownies";
		price = Kfc.getmealPrice(mealName26);
		System.out.println("The meal name is " +mealName26+ " with price is " +price);
		String mealName27 = "Chicken Strips";
		price = Kfc.getmealPrice(mealName27);
		System.out.println("The meal name is " +mealName27+ " with price is " +price);
		String mealName28 = "Hot Wings";
		price = Kfc.getmealPrice(mealName28);
		System.out.println("The meal name is " +mealName28+ " with price is " +price);
		String mealName29 = "peri peri Chicken";
		price = Kfc.getmealPrice(mealName29);
		System.out.println("The meal name is " +mealName29+ " with price is " +price);
		String mealName30 = "Smoky Red Chicken";
		price = Kfc.getmealPrice(mealName30);
		System.out.println("The meal name is " +mealName30+ " with price is " +price);
		
		
	}
}
