class SwiggyAppRunner {
	public static void main(String swiggy[]){
		//double price;
		String foodName1 = "Mini Idli";
		 double price = SwiggyApp.getfoodCost(foodName1);
		System.out.println("The cost of "+foodName1+" is "+price);
		String foodName2 = "Butter Masala Dosa";
	     price = SwiggyApp.getfoodCost(foodName2);
		System.out.println("The cost of "+foodName2+" is "+price);
		String foodName3 = "Bun Butter Jam";
		 price = SwiggyApp.getfoodCost(foodName3);
		System.out.println("The cost of "+foodName3+" is "+price);
		String foodName4 = "Tea";
		price = SwiggyApp.getfoodCost(foodName4);
		System.out.println("The cost of "+foodName4+" is "+price);
		String foodName5 = "Coffee";
		price = SwiggyApp.getfoodCost(foodName5);
		System.out.println("The cost of "+foodName5+" is "+price);
		String foodName6 = "Small Samosa";
		price = SwiggyApp.getfoodCost(foodName6);
		System.out.println("The cost of "+foodName6+" is "+price);
		String foodName7 = "Plain Dosa";
		price = SwiggyApp.getfoodCost(foodName7);
		System.out.println("The cost of "+foodName7+" is "+price);
		String foodName8 = "Onion Pakoda";
		price = SwiggyApp.getfoodCost(foodName8);
		System.out.println("The cost of "+foodName8+" is "+price);
		String foodName9 = "Puri";
		price = SwiggyApp.getfoodCost(foodName9);
		System.out.println("The cost of "+foodName9+" is "+price);
		String foodName10 = "Veg Puff";
		price = SwiggyApp.getfoodCost(foodName10);
		System.out.println("The cost of "+foodName10+" is "+price);
		String foodName11 = "Masala Puri";
		price = SwiggyApp.getfoodCost(foodName11);
		System.out.println("The cost of "+foodName11+" is "+price);
		String foodName12 = "Sweet Lassi";
		price = SwiggyApp.getfoodCost(foodName12);
		System.out.println("The cost of "+foodName12+" is "+price);
		String foodName13 = "Filter Coffee";
		price = SwiggyApp.getfoodCost(foodName13);
		System.out.println("The cost of "+foodName13+" is "+price);
		String foodName14 = "Plain Rava Idli";
		price = SwiggyApp.getfoodCost(foodName14);
		System.out.println("The cost of "+foodName14+" is "+price);
		String foodName15 = "Lemon Tea";
		price = SwiggyApp.getfoodCost(foodName15);
		System.out.println("The cost of "+foodName15+" is "+price);
		String foodName16 = "Small Vada";
		price = SwiggyApp.getfoodCost(foodName16);
		System.out.println("The cost of "+foodName16+" is "+price);
		String foodName17 = "Veg Noodles";
		price = SwiggyApp.getfoodCost(foodName17);
		System.out.println("The cost of "+foodName17+" is "+price);
		String foodName18 = "Veg Fried Rice";
		price = SwiggyApp.getfoodCost(foodName18);
		System.out.println("The cost of "+foodName18+" is "+price);
		String foodName19 = "Chilli Chicken";
		price = SwiggyApp.getfoodCost(foodName19);
		System.out.println("The cost of "+foodName19+" is "+price);
		String foodName20 = "Chicken Biryani";
		price = SwiggyApp.getfoodCost(foodName20);
		System.out.println("The cost of "+foodName20+" is "+price);
		String foodName21 = "Chicken65";
		price = SwiggyApp.getfoodCost(foodName21);
		System.out.println("The cost of "+foodName21+" is "+price);
		String foodName22 = "Veg Biryani";
		price = SwiggyApp.getfoodCost(foodName22);
		System.out.println("The cost of "+foodName22+" is "+price);
		String foodName23 = "Noodles";
		price = SwiggyApp.getfoodCost(foodName23);
		System.out.println("The cost of "+foodName23+" is "+price);
		String foodName24 = "Fried Rice";
		price = SwiggyApp.getfoodCost(foodName24);
		System.out.println("The cost of "+foodName24+" is "+price);
		String foodName25 = "Paneer Butter Masala";
		price = SwiggyApp.getfoodCost(foodName25);
		System.out.println("The cost of "+foodName25+" is "+price);
		String foodName26 = "Dal Makhani";
		price = SwiggyApp.getfoodCost(foodName26);
		System.out.println("The cost of "+foodName26+" is "+price);
		String foodName27 = "Gobi Manchurian";
		price = SwiggyApp.getfoodCost(foodName27);
		System.out.println("The cost of "+foodName27+" is "+price);
		String foodName28 = "Mutton Biryani";
		price = SwiggyApp.getfoodCost(foodName28);
		System.out.println("The cost of "+foodName28+" is "+price);
		String foodName29 = "Boiled Egg";
		price = SwiggyApp.getfoodCost(foodName29);
		System.out.println("The cost of "+foodName29+" is "+price);
		String foodName30 = "Thali";
		price = SwiggyApp.getfoodCost(foodName30);
		System.out.println("The cost of "+foodName30+" is "+price);
	}
}
