class UberEatsRunner {
	public static void main (String chand[]){
	String foodName1 = "Veg kurma";
    double price = UberEats.getFoodCost(foodName1);
    System.out.println(" The FoodName is " +foodName1+ " with cost of " +price);
	String foodName2 = "SavigeBath";
    price = UberEats.getFoodCost(foodName2);
    System.out.println(" The FoodName is " +foodName2+ " with cost of " +price);
	String foodName3 = "KaraBath";
    price = UberEats.getFoodCost(foodName3);
    System.out.println(" The FoodName is " +foodName3+ " with cost of " +price);
	String foodName4 = "Roti";
    price = UberEats.getFoodCost(foodName4);
    System.out.println(" The FoodName is " +foodName4+ " with cost of " +price);
	String foodName5 = "Chappati";
    price = UberEats.getFoodCost(foodName5);
    System.out.println(" The FoodName is " +foodName5+ " with cost of " +price);
	String foodName6 = "Parota";
    price = UberEats.getFoodCost(foodName6);
    System.out.println(" The FoodName is " +foodName6+ " with cost of " +price);
	String foodName7 = "Paneer Curry";
    price = UberEats.getFoodCost(foodName7);
    System.out.println(" The FoodName is " +foodName7+ " with cost of " +price);
	String foodName8 = "Masala Dosa";
    price = UberEats.getFoodCost(foodName8);
    System.out.println(" The FoodName is " +foodName8+ " with cost of " +price);
	String foodName9 = "Chakna fry";
    price = UberEats.getFoodCost(foodName9);
    System.out.println(" The FoodName is " +foodName9+ " with cost of " +price);
	String foodName10 = "Jamun";
    price = UberEats.getFoodCost(foodName10);
    System.out.println(" The FoodName is " +foodName10+ " with cost of " +price);
	String foodName11 = "Sweet";
    price = UberEats.getFoodCost(foodName11);
    System.out.println(" The FoodName is " +foodName11+ " with cost of " +price);
	String foodName12 = "Mushroom Kabab";
    price = UberEats.getFoodCost(foodName12);
    System.out.println(" The FoodName is " +foodName12+ " with cost of " +price);
	String foodName13 = "Jeera Rice";
    price = UberEats.getFoodCost(foodName13);
    System.out.println(" The FoodName is " +foodName13+ " with cost of " +price);
	String foodName14 = "Fried Rice";
    price = UberEats.getFoodCost(foodName14);
    System.out.println(" The FoodName is " +foodName14+ " with cost of " +price);
	String foodName15 = "veg Uppit";
    price = UberEats.getFoodCost(foodName15);
    System.out.println(" The FoodName is " +foodName15+ " with cost of " +price);
	String foodName16 = "Vada";
    price = UberEats.getFoodCost(foodName16);
    System.out.println(" The FoodName is " +foodName16+ " with cost of " +price);
	String foodName17 = "bonda";
    price = UberEats.getFoodCost(foodName17);
    System.out.println(" The FoodName is " +foodName17+ " with cost of " +price);
	String foodName18 = "Veg Soup";
    price = UberEats.getFoodCost(foodName18);
    System.out.println(" The FoodName is " +foodName18+ " with cost of " +price);
	String foodName19 = "corn Fry";
    price = UberEats.getFoodCost(foodName19);
    System.out.println(" The FoodName is " +foodName19+ " with cost of " +price);
	String foodName20 = "Puri";
    price = UberEats.getFoodCost(foodName20);
    System.out.println(" The FoodName is " +foodName20+ " with cost of " +price);
	String foodName21 = "Puliyogre";
    price = UberEats.getFoodCost(foodName21);
    System.out.println(" The FoodName is " +foodName21+ " with cost of " +price);
	String foodName22 = "LemonRice";
    price = UberEats.getFoodCost(foodName22);
    System.out.println(" The FoodName is " +foodName22+ " with cost of " +price);
	String foodName23 = "Mango Dosa";
    price = UberEats.getFoodCost(foodName23);
    System.out.println(" The FoodName is " +foodName23+ " with cost of " +price);
	String foodName24 = "Girmit";
    price = UberEats.getFoodCost(foodName24);
    System.out.println(" The FoodName is " +foodName24+ " with cost of " +price);
	String foodName25 = "Pani Puri";
    price = UberEats.getFoodCost(foodName25);
    System.out.println(" The FoodName is " +foodName25+ " with cost of " +price);
	String foodName26 = "Baby Corn Manchurian";
    price = UberEats.getFoodCost(foodName26);
    System.out.println(" The FoodName is " +foodName26+ " with cost of " +price);
	String foodName27 = "northern meals";
    price = UberEats.getFoodCost(foodName27);
    System.out.println(" The FoodName is " +foodName27+ " with cost of " +price);
	String foodName28 = "Southern Meals";
    price = UberEats.getFoodCost(foodName28);
    System.out.println(" The FoodName is " +foodName28+ " with cost of " +price);
	String foodName29 = "beeda";
    price = UberEats.getFoodCost(foodName29);
    System.out.println(" The FoodName is " +foodName29+ " with cost of " +price);
	String foodName30 = "Rasgoola";
    price = UberEats.getFoodCost(foodName30);
    System.out.println(" The FoodName is " +foodName30+ " with cost of " +price);
	}
}

	
    	
