class ZomatoAppRunner{
	public static void main(String chand[]){
		String foodName1 = "bajji";
		double price = ZomatoApp.getFoodCost(foodName1);
		System.out.println("The food Name is " +foodName1+ " with cost of " +price);
		String foodName2 = "RiceBath";
	    price = ZomatoApp.getFoodCost(foodName2);
		System.out.println("The food Name is " +foodName2+ " with cost of " +price);
		String foodName3 = "Vegetable Samosa";
	    price = ZomatoApp.getFoodCost(foodName3);
		System.out.println("The food Name is " +foodName3+ " with cost of " +price);
		String foodName4 = "Chicken 65";
	    price = ZomatoApp.getFoodCost(foodName4);
		System.out.println("The food Name is " +foodName4+ " with cost of " +price);
		String foodName5 = "French Fries";
	    price = ZomatoApp.getFoodCost(foodName5);
		System.out.println("The food Name is " +foodName5+ " with cost of " +price);
		String foodName6 = "Onion Rings";
	    price = ZomatoApp.getFoodCost(foodName6);
		System.out.println("The food Name is " +foodName6+ " with cost of " +price);
		String foodName7 = "Vegetable Spring Rolls";
	    price = ZomatoApp.getFoodCost(foodName7);
		System.out.println("The food Name is " +foodName7+ " with cost of " +price);
		String foodName8 = "Chicken lolipop";
	    price = ZomatoApp.getFoodCost(foodName8);
		System.out.println("The food Name is " +foodName8+ " with cost of " +price);
		String foodName9 = "Cheese Maggi";
	    price = ZomatoApp.getFoodCost(foodName9);
		System.out.println("The food Name is " +foodName9+ " with cost of " +price);
		String foodName10 = "Corn Chat";
	    price = ZomatoApp.getFoodCost(foodName10);
		System.out.println("The food Name is " +foodName10+ " with cost of " +price);
		String foodName11 = "Veggi Burger";
	    price = ZomatoApp.getFoodCost(foodName11);
		System.out.println("The food Name is " +foodName11+ " with cost of " +price);
		String foodName12 = "Chicken Burger";
	    price = ZomatoApp.getFoodCost(foodName12);
		System.out.println("The food Name is " +foodName12+ " with cost of " +price);
		String foodName13 = "Paneer tikka";
	    price = ZomatoApp.getFoodCost(foodName13);
		System.out.println("The food Name is " +foodName13+ " with cost of " +price);
		String foodName14 = "Chicken tikka";
	    price = ZomatoApp.getFoodCost(foodName14);
		System.out.println("The food Name is " +foodName14+ " with cost of " +price);
		String foodName15 = "Butter Naan";
	    price = ZomatoApp.getFoodCost(foodName15);
		System.out.println("The food Name is " +foodName15+ " with cost of " +price);
		String foodName16 = "Palak Paneer";
	    price = ZomatoApp.getFoodCost(foodName16);
		System.out.println("The food Name is " +foodName16+ " with cost of " +price);
		String foodName17 = "Veg fried Rice";
	    price = ZomatoApp.getFoodCost(foodName17);
		System.out.println("The food Name is " +foodName17+ " with cost of " +price);
		String foodName18 = "Veg Noodles";
	    price = ZomatoApp.getFoodCost(foodName18);
		System.out.println("The food Name is " +foodName18+ " with cost of " +price);
		String foodName19 = "Paneer Manchurian";
	    price = ZomatoApp.getFoodCost(foodName19);
		System.out.println("The food Name is " +foodName19+ " with cost of " +price);
		String foodName20 = "Egg Rice";
	    price = ZomatoApp.getFoodCost(foodName20);
		System.out.println("The food Name is " +foodName20+ " with cost of " +price);
		String foodName21 = "Jeera Rice";
	    price = ZomatoApp.getFoodCost(foodName21);
		System.out.println("The food Name is " +foodName21+ " with cost of " +price);
		String foodName22 = "Pasta";
	    price = ZomatoApp.getFoodCost(foodName22);
		System.out.println("The food Name is " +foodName22+ " with cost of " +price);
		String foodName23 = "Rice Sambar";
	    price = ZomatoApp.getFoodCost(foodName23);
		System.out.println("The food Name is " +foodName23+ " with cost of " +price);
		String foodName24 = "North Meals";
	    price = ZomatoApp.getFoodCost(foodName24);
		System.out.println("The food Name is " +foodName24+ " with cost of " +price);
		String foodName25 = "Uppit";
	    price = ZomatoApp.getFoodCost(foodName25);
		System.out.println("The food Name is " +foodName25+ " with cost of " +price);
		String foodName26 = "Kara Pongal";
	    price = ZomatoApp.getFoodCost(foodName26);
		System.out.println("The food Name is " +foodName26+ " with cost of " +price);
		String foodName27 = "Sweet Pongal";
	    price = ZomatoApp.getFoodCost(foodName27);
		System.out.println("The food Name is " +foodName27+ " with cost of " +price);
		String foodName28 = "KesariBath";
	    price = ZomatoApp.getFoodCost(foodName28);
		System.out.println("The food Name is " +foodName28+ " with cost of " +price);
		String foodName29 = "Paluv";
	    price = ZomatoApp.getFoodCost(foodName29);
		System.out.println("The food Name is " +foodName29+ " with cost of " +price);
		String foodName30 = "Bonda";
	    price = ZomatoApp.getFoodCost(foodName30);
		System.out.println("The food Name is " +foodName30+ " with cost of " +price);
	}
}